wordlist = "/usr/share/seclists/Discovery/Web-Content/raft-medium-words.txt"
status_codes = [200, 204, 301, 302, 307, 401, 403, 405, 500]
filter_status = [404, 400]
threads = 40
timeout = 10
verbosity = 2
parallel = 16
scan_limit = 12
rate_limit = 0
quiet = false
auto_tune = true
extensions = ["php", "txt", "log", "bak", "old", "zip", "tar", "conf", "inc", "swp"]
extract_links = true
save_state = false
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
random_agent = true
output = "/tmp/feroxbuster_results.txt"
# debug_log = "/var/log/feroxbuster-debug.log"
# redirects = true
# insecure = true