# Minimal Dark Mode Configuration for Alacritty

import = []

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.95
decorations_theme_variant = "Dark"

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }
size = 18.0

[colors]
[colors.primary]
foreground = "#d0d0d0"
background = "#000000"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black = "#000000"
red = "#ff5f5f"
green = "#87d700"
yellow = "#ffd700"
blue = "#5f87ff"
magenta = "#875fd7"
cyan = "#5fafd7"
white = "#d0d0d0"

[colors.bright]
black = "#4e4e4e"
red = "#ff8700"
green = "#afff00"
yellow = "#ffaf00"
blue = "#8787ff"
magenta = "#af87ff"
cyan = "#87d7ff"
white = "#e4e4e4"

[colors.dim]
black = "#262626"
red = "#af5f5f"
green = "#5f875f"
yellow = "#87875f"
blue = "#5f5f87"
magenta = "#875f87"
cyan = "#5f8787"
white = "#8a8a8a"

[scrolling]
history = 10000
multiplier = 3